- name: print course from files
  hosts: frontend
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course from files
    ansible.builtin.debug:
      msg: "course name is {{ COURSE }}, Duration {{ DURATION }}, Trainer is {{ TRAINER }}"