- name: vars preference
  hosts: frontend
  vars:
    NAME: from play level
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: What is your NAME?
    private:  false
  tasks:
  - name: testing variable preference
    vars:
      NAME: from task level
    ansible.builtin.debug:
      msg:  "Name: {{NAME}}"